### ISSUE TITLE
Dynamic module resolution in socket.io < 3 prevents use with Webpack

### ISSUE THREAD

**Issue by jojonas** [ambelovsky/koa-socket-2#21]
I am indirectly using koa-socket-2 via https://github.com/boardgameio/boardgame.io. 
Unfortunately, socket.io before version 3.0.0 (koa-socket-2 requires 2.3.0) has a bug which prevents it from being used with TypeScript and Webpack (not sure which one causes the error). Compilation already generates a warning:

```
WARNING in ./node_modules/koa-socket-2/node_modules/socket.io/lib/index.js 113:11-32
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/koa-socket-2/index.js 4:17-39
 @ ./node_modules/boardgame.io/dist/cjs/server.js 13:25-48
 @ ./src/server.ts 1:0-45 3:15-21
```

Execution subsequently results in the following message:

```
webpack://[redacted]/./node_modules/koa-socket-2/node_modules/socket.io/lib/_sync?:4
        throw e;
        ^
Error: Cannot find module 'socket.io-client/dist/socket.io.js'
    at Function.webpackEmptyContext [as resolve] (webpack://[redacted]/./node_modules/koa-socket-2/node_modules/socket.io/lib/_sync?:2:10)
    at resolvePath (webpack://[redacted]/./node_modules/koa-socket-2/node_modules/socket.io/lib/index.js?:113:125)
    at Server.serveClient (webpack://[redacted]/./node_modules/koa-socket-2/node_modules/socket.io/lib/index.js?:116:25)
    at new Server (webpack://[redacted]/./node_modules/koa-socket-2/node_modules/socket.io/lib/index.js?:53:8)
    at IO.attach (webpack://[redacted]/./node_modules/koa-socket-2/index.js?:132:15)
    at SocketIO.init (webpack://[redacted]/./node_modules/boardgame.io/dist/cjs/server.js?:3163:12)
    at Server (webpack://[redacted]/./node_modules/boardgame.io/dist/cjs/server.js?:3264:15)
    at eval (webpack://[redacted]/./src/server.ts?:6:75)
    at Module../src/server.ts ([redacted]/dist/server.js:31834:1)
    at __webpack_require__ ([redacted]/dist/server.js:32492:42) {
  code: 'MODULE_NOT_FOUND'
```

The cause is a dynamic import which is used by the socket.io server to serve the compiled client code too (see https://github.com/socketio/socket.io/blob/47161a65d40c2587535de750ac4c7d448e5842ba/lib/index.js#L113). The dynamic import cannot be correctly handled by Webpack which is why the imported file is not included in the bundle.

I haven't tested it yet but it looks like the issue has been accidentally resolved through this commit:

https://github.com/socketio/socket.io/commit/7603da71a535481e3fc60e38b013abf78516d322#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567L228

For koa-socket-2 I see two possible solutions to this issue: Either to upgrade socket.io to version 3.0 or to disable to serve the client code, which can be achieved by importing socket.io as follows:

`const io = require('socket.io')(server, {
  serveClient: false,
});`

Would the second solution be feasible for koa-socket-2 or do users depend on the client code being served through socket.io?

**Comment by ambelovsky** [comment]
Sounds good.  Let’s get it upgraded!

**Comment by jojonas** [comment]
Socket.io has a pretty decent migration guide: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/

I can try to do the migration and contribute a pull request if you want. But as I'm only indirectly using this library I'm not sure whether I can test the changes properly.

**Comment by ambelovsky** [comment]
Great work, Jonas!  Thanks for the contribution!  I've added you to the contributors section of the documentation.

**Comment by ambelovsky** [comment]
Koa-Socket-2 v2.0.0 Published:
https://www.npmjs.com/package/koa-socket-2
